### ISSUE TITLE
Extract samples into their own repos

### ISSUE THREAD

**Issue by MaxHatfull** [rubyrpg/ruby_rpg#15]
This way the games can require ruby_rpg as a gem and use the commands and tools provided whilst keeping the game code seperate from the gem itself.

**Comment by GetOutOfMyBakery** [comment]
It might be better off creating a new org for this project, and having all the repos be included in that org.

**Comment by MaxHatfull** [comment]
For the games in the repo I think I'll leave them there, it's nice having the tests really close to the engine to speed up iteration. I can add new sample games to the org as they come up for examples and documentation (and fun!)
